version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: doc/requirements.txt
    - method: pip
      path: .
