name: 🐛 Bug report
description: Create a report to help us improve
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: bandit-version
    attributes:
      label: Bandit version
      description: Run "bandit --version" if unsure of version number
      options:
        - 1.9.1 (Default)
        - 1.9.0
        - 1.8.6
        - 1.8.5
        - 1.8.4
        - 1.8.3
        - 1.8.2
        - 1.8.1
        - 1.8.0
        - 1.7.10
        - 1.7.9
        - 1.7.8
        - 1.7.7
        - 1.7.6
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: Run "bandit --version" if unsure of version number
      options:
        - "3.14 (Default)"
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
