name: Upload wheel asset

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and upload wheel as asset
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install setuptools wheel

    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940
      with:
        subject-path: 'dist/bandit-*'
