name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Lint with pylint
      run: |
        pylint --rcfile=pylintrc bandit
    - name: Lint with flake8
      run: |
        flake8 . --show-source --exclude=.venv,.git,.tox,dist,doc,*lib/python*,*egg,build,releasenotes --enable-extensions=H106,H203 bandit
        flake8 . --show-source --exclude=.venv,.git,.tox,dist,doc,*lib/python*,*egg,build,releasenotes --enable-extensions=H106,H203 tests
    - name: Test with stestr
      run: |
        stestr run
    - name: Build docs
      run: |
        python setup.py build_sphinx
