name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]
        include:
          - os: ubuntu-18.04
            python: 2.7
            env: TOXENV=pylint
          - os: ubuntu-18.04
            python: 2.7
            env: TOXENV=pep8
          - os: ubuntu-18.04
            python: 2.7
            env: TOXENV=py27
          - os: ubuntu-18.04
            python: 3.5
            env: TOXENV=py35
          - os: ubuntu-18.04
            python: 3.6
            env: TOXENV=py36
          - os: ubuntu-18.04
            python: 3.7
            env: TOXENV=py37
          - os: ubuntu-18.04
            python: pypy
            env: TOXENV=pypy

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        pip install tox
    - name: Run tox
      run: tox
